s=input("Enter your name:")
print(s)
print(f'Type of {s} is {type(s)}')
print(f'ID of {s} is {id(s)}')
print(f'Max of {s} is {max(s)}')
print(f'Min of {s} is {min(s)}')
print(f'Length of {s} is {len(s)}')